name = "ExamplePackage"
uuid = "280408a6-513e-4226-ae12-07abfacb7358"
authors = ["Zining-Liu <71028840+Zining-Liu@users.noreply.github.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
